OBJS    = Comparators.java AbstractHeap.java AbstractQueue.java Heap.java PriorityQueue.java Main.java
CC  = javac

all: $(OBJS)

	$(CC) $(OBJS)

clean:
	rm -f IntegerComparator.class StringComparator.class AbstractHeap.class AbstractQueue.class Heap.class PriorityQueue.class Main.class