#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <unistd.h>
#include <sys/wait.h>
#include <sys/shm.h>
#include <errno.h>
#include <string.h>

int m_id;

// shared data structure
struct shared
{
    int num;
    char k;
    double d;
};
int main()
{
    struct shared *sh;
    // get id of shared memory
    m_id = shmget(IPC_PRIVATE, sizeof(struct shared), 0600);
    int shmctl(m_id, IPC_RMID, NULL);
    sh = shmat(m_id, NULL, 0);
    // attach shared memory to a struct

    sh->num = 10;
    sh->k = 'a';
    sh->d = 20.0;

    for (int i = 0; i < 2; i++)
    {
        switch (fork())
        {
        case -1:
            /* Handle error */
            fprintf(stderr, "Error #%03d: %s\n", errno, strerror(errno));
            break;

        case 0:
            sh = shmat(m_id, NULL, 0);
            printf("%d, %c, %lf\n", sh->num, sh->k, sh->d);
            // detached shared memory segment
            shmdt(sh);
            exit(EXIT_SUCCESS); // exit the process after the first execution, prevent the spawn of multiple useless process
            break;
        }
    }

    shmdt(sh);
}

/*  Shared memory
*   shmeg provide the id of the shared memory segment. The segment can be brand new with IPC_CREATE or generated by a given key.
*   shmctl control the general behaviour of the segment
        -IPC_STAT: Copy information from the kernel data structure associated with shmid into the shmid_ds structure pointed to by buf.
             shmctl(int shmid, int cmd, struct shmid_ds *buf);
             The shim_ds provide information such as pid of the segment and attach and detach time
        -IPC_SET: Write the values of some members of the shmid_ds structure
        -IPC_RMID: Mark the segment to be destroyed.  The segment will actually be destroyed only after the last process detaches it
        -IPC_INFO: Return information about system-wide shared memory limits and parameters in the structure pointed to by buf. the name of the structure is shminfo
        -SHM_INFO: Return a shm_info structure whose fields contain information about system resources consumed by shared memory.
        -SHM_LOCK - SHM_UNLOCK: prevent-allow swapping of the shared memory segment.

     struct shmid_ds {
               struct ipc_perm shm_perm;     Ownership and permissions
               size_t          shm_segsz;    Size of segment (bytes)
               time_t          shm_atime;    Last attach time
               time_t          shm_dtime;    Last detach time
               time_t          shm_ctime;    Creation time/time of last
                                               modification via shmctl()
               pid_t           shm_cpid;     PID of creator
               pid_t           shm_lpid;     PID of last shmat(2)/shmdt(2)
               shmatt_t        shm_nattch;   No. of current attaches
               ...
           };

    struct shminfo {
                      unsigned long shmmax;  Maximum segment size 
                      unsigned long shmmin;  Minimum segment size;
                                               always 1 
                      unsigned long shmmni;  Maximum number of segments 
                      unsigned long shmseg;  Maximum number of segments
                                               that a process can attach;
                                               unused within kernel 
                      unsigned long shmall;  Maximum number of pages of
                                               shared memory, system-wide 
                  };
    Permission:
    0400   Read by user
    0200   Write by user
    0040   Read by group
    0020   Write by group
    0004   Read by others
    0002   Write by others
*/